version: '3'

services:
  redis:
    image: redis:7.2.3
    container_name: PhocaFormeRedis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mariadb:
    image: mariadb:10.11.6
    container_name: PhocaFormeMariaDB
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/lib/var/mysql
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${USER_NAME}
      MARIADB_PASSWORD: ${USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Asia/Seoul
  rabbitmq:
    image: rabbitmq:management
    container_name: PhocaFormeRabbitMQ
    ports:
      - "5672:5672"  # RabbitMQ server
      - "15672:15672"  # Management interface
    restart: unless-stopped
volumes:
  redis-data:
  mariadb-data:

