spring:
  config:
    activate:
      on-profile: ssafy
  jpa:
    hibernate:

#      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  # DB 연결
  datasource:
    # 설치된 H2 DB와 연결 URL
    url: ${DB_URL}
    # 접속을 위한 드라이버
    driver-class-name: org.mariadb.jdbc.Driver
    # springboot 2.4 부터는 username이 꼭 있어야합니다. 없으면 에러가 발생.
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
  data:
    redis:
      host: localhost # Redis 서버 호스트 주소
      port: 6379      # Redis 서버 포트
      database: 0
jwt:
  secret: 'jxgEQeXHuPq8VdbyYFNkANdudQ53YUn4'
logging:
  level:
    org:
      springframework:
        security: DEBUG
project:
  url: http://localhost:8080
  API-URL: https://fcm.googleapis.com/v1/projects/phocaforme/messages:send