spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/application-ssafy-dev.yml
      - classpath:/application-oauth.yml
      - classpath:/application-aws.yml
  profiles:
    active: ssafy, oauth, aws