spring:
  config:
    import:
      - optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    url: ${DB_URL}
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver