spring:
  rabbitmq:
    host: phocafor.me
    port: 3000
    username: guest
    password: guest

rabbitmq:
  queue:
    name: your_queue_name
  exchange:
    name: your_exchange_name
  routing:
    key: your_routing_key
