server:
  port: 4885

---
spring:
  config:
    activate:
      on-profile: global
    import:
      - optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PhocaForMe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: youRmybias1004
  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print