spring:
  rabbitmq:
    host: phocafor.me
    port: 5672
    username: guest
    password: guest


#rabbitmq:
#  queue:
#    name: your_queue_name
#  exchange:
#    name: your_exchange_name
#  routing:
#    key: your_routing_key
