spring:
  config:
    activate:
      on-profile: oauth
  # 스프링 시큐리티
  security:
    # oauth2 사용
    oauth2:
      # client
      client:
        # 등록 부분 설정
        registration:
          kakao:
            client-id: 0c667ea3c8f35cc83690ec0c37f136e2
            client-secret: 4SxLoXSuTBMJJCxseJ27jKCZsF8jeMSi
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://i10a703.p.ssafy.io:4885/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
auth-redirect-url: https://i10a073.p.ssafy.io:8888