spring:
  config:
    activate:
      on-profile: oauth
  # 스프링 시큐리티
  security:
    # oauth2 사용
    oauth2:
      # client
      client:
        # 등록 부분 설정
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            client-authentication-method: client_secret_post
            scope: profile_nickname, account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
auth-redirect-url: ${AUTH_REDIRECT_URL}

