server:
  port: 4885

---
spring:
  config:
    activate:
      on-profile: global
    import:
      - optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i10a703.p.ssafy.io:3306/PhocaForMe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: youRmybias1004
  security:
    user:
      name: phocaforme
      password: 12345
