server:
  port: 4885

---
spring:
  config:
    activate:
      on-profile: global
    import:
      - optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PhocaForMe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${GLOBAL_USER_NAME}
    password: ${GLOBAL_USER_PASSWORD}
