spring:
  config:
    activate:
      on-profile: aws

cloud:
  aws:
    s3:
      bucket: photocardforme
      base-url: https://photocardforme.s3.ap-northeast-2.amazonaws.com/
    credentials:
      access-key: AKIAQHA7BQHU4JZDO5U3
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false