spring:
  config:
    import:
      - optional:file:.env[.properties]
      - classpath:/application-ssafy-dev.yml
      - classpath:/application-oauth.yml
      - classpath:/application-rabbit.yml
      - classpath:/application-elastic.yml
  profiles:
    active: ssafy, oauth, aws, rabbit, elastic